application: uosdeedim
version: 1
runtime: python27
api_version: 1
threadsafe : true

handlers:
- url: /static
  static_dir: static
  
- url: /static/image
  static_dir: static/image

- url: /static/js
  static_dir: static/js
    
- url: /.*
  script: helloworld.application
